In [1]:
import random

#Pennylane
import pennylane as qml
from pennylane import numpy as np

#PyTorch
import torch
import torchvision
from torchvision import datasets, transforms

In [2]:
dev = qml.device('default.qubit', wires = 6)
n_qubits = 6
n_layer_steps = 5
n_layers_to_add = 2
dim = 2**(n_qubits)

In [3]:
def set_random_gates(n_qubits: int):
    
    gate_set = [qml.RX, qml.RY, qml.RZ]
    chosen_gates = []
    for i in range(n_qubits):
        chosen_gate = random.choice(gate_set)
        chosen_gates.append(chosen_gate)
    return chosen_gates

def norm(complex_vector: np.array) -> float:
    """Returns the norm of a complex vector.
    
    Args:
       complex_vector (np.arrray of shape (dim,)):
           complex vector with an arbitrary dimension.
           
       
    Returns:
        norm (float): norm or magnitude of the complex vector.
            
    """
    
    #define the norm of a complex vector here
    norm = np.sqrt(sum([np.square(np.absolute(complex_vector[i])) for i in range(complex_vector.shape[0])]))
    
    return norm

def random_quantum_state(dim: int, amplitude_type: str = 'complex') -> np.array:
    """Creates a normalized random real or complex vector of a defined
    dimension.
    
    Args:
        dim (int): integer number specifying the dimension
            of the vector that we want to generate.
            
        amplitude_type (str): string indicating if you want to create a
            vector with 'complex' or 'real' number amplitudes.
            
    Returns:
        (np.array): normalized real or complex vector of the given
            dimension.
    """
    #generate an unnormalized complex vector of dimension = dim
    if amplitude_type == 'complex':
        Z = np.random.random(dim) + np.random.random(dim)*1j
    
    #generate an unnormalized real vector of dimension = dim
    elif amplitude_type == 'real':
        Z = np.random.random(dim)
    
    #normalize the complex vector Z
    Z /= norm(Z)
    
    return Z

def density_matrix(target_vector: np.array) -> np.array:
    """Return the density matrix of a pure state.
    
    Arguments:
        target_vector (np.array): Complex vector array.
        
    Returns:
        (np.array): Density matrix of shape (dim, dim),
            where dim is the dimension of the target_vector.
    """
    target_vector_reshape = target_vector.reshape((target_vector.shape[0],1))
    density_matrix = target_vector_reshape @ np.transpose(np.conjugate(target_vector_reshape))
    
    return density_matrix

In [4]:
target_vector = random_quantum_state(dim)
density_matrix = density_matrix(target_vector)

### Templates for Phase I

In [5]:
@qml.template
def apply_layer(gates, weights):
    
    for i in range(n_qubits):
        gates[i](weights[i], wires = i)
    
    tuples = [(i,i+1) for i in range(n_qubits-1)]

    for tup in tuples:
        qml.CZ(wires=[tup[0], tup[1]])
        
@qml.template #template for non-trainable part of the quantum circuit
def frozen_layers(frozen_layer_gates, frozen_layer_weights): 

    for i in range(len(frozen_layer_gates)):
        apply_layer(frozen_layer_gates[i], frozen_layer_weights[i])

@qml.qnode(dev)
def trainable_circuit(params):
    
    #apply frozen layers
    frozen_layers(layer_gates, layer_weights)
    
    #apply trainable layers
    new_weights = []
    for i in range(n_layers_to_add):
        new_weights.append(params[int(i*n_qubits):int((i+1)*n_qubits)])

    for i in range(n_layers_to_add):
        apply_layer(new_gates[i], new_weights[i])
        
    wirelist = [i for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix, wirelist))

In [6]:
def cost(x):
    
    return (1.0 - trainable_circuit(x))

In [7]:
layer_gates = []
layer_weights = []
n_layers = 2
for i in range(n_layers):
    layer_gates.append(set_random_gates(n_qubits))
    layer_weights.append(np.random.rand(n_qubits)*2*np.pi)
    
new_gates = [set_random_gates(n_qubits) for i in range(n_layers_to_add)]
params = np.random.rand(n_qubits*n_layers_to_add)*2*np.pi

trainable_circuit(params)

0.0005280991690744316

In [8]:
layer_gates = []
layer_weights = []
cost_list = []
for step in range(n_layer_steps):
    
    new_gates = [set_random_gates(n_qubits) for i in range(n_layers_to_add)]
    init_params = np.zeros(n_qubits*n_layers_to_add)
    
    opt = qml.GradientDescentOptimizer(stepsize = 0.4)

    opt_steps = 100

    params = init_params
    
    for i in range(opt_steps):

        params = opt.step(cost, params)
    
    
    print(step)
    print(layer_weights)
    print(cost(params))
    cost_list.append(cost(params))
    
    trained_weights = [params[int(i*n_qubits):int((i+1)*n_qubits)] for i in range(n_layers_to_add)]
    
    layer_gates += new_gates
    layer_weights += trained_weights

0
[]
0.93790310126802
1
[array([-3.33066907e-17, -3.33066907e-17, -3.33066907e-17, -6.44598553e-01,
        7.11039243e-01,  5.38960658e-02]), array([ 5.93853627e-01, -1.11022302e-17, -1.11022302e-17, -4.05852921e-01,
        4.77207735e-01, -1.78902765e-01])]
0.8064175042627909
2
[array([-3.33066907e-17, -3.33066907e-17, -3.33066907e-17, -6.44598553e-01,
        7.11039243e-01,  5.38960658e-02]), array([ 5.93853627e-01, -1.11022302e-17, -1.11022302e-17, -4.05852921e-01,
        4.77207735e-01, -1.78902765e-01]), array([ 0.05616862, -0.86518922, -0.81036041, -0.4441426 ,  0.09794083,
        0.19445019]), array([-0.87340292, -0.30521581, -0.74609603, -0.4441426 ,  0.27872414,
        0.26348358])]
0.6004716553915825
3
[array([-3.33066907e-17, -3.33066907e-17, -3.33066907e-17, -6.44598553e-01,
        7.11039243e-01,  5.38960658e-02]), array([ 5.93853627e-01, -1.11022302e-17, -1.11022302e-17, -4.05852921e-01,
        4.77207735e-01, -1.78902765e-01]), array([ 0.05616862, -0.86518922, -0

In [9]:
layer_weights

[array([-3.33066907e-17, -3.33066907e-17, -3.33066907e-17, -6.44598553e-01,
         7.11039243e-01,  5.38960658e-02]),
 array([ 5.93853627e-01, -1.11022302e-17, -1.11022302e-17, -4.05852921e-01,
         4.77207735e-01, -1.78902765e-01]),
 array([ 0.05616862, -0.86518922, -0.81036041, -0.4441426 ,  0.09794083,
         0.19445019]),
 array([-0.87340292, -0.30521581, -0.74609603, -0.4441426 ,  0.27872414,
         0.26348358]),
 array([ 0.24794572, -0.07122497,  1.08325849, -0.20645333, -0.0084622 ,
         1.25011822]),
 array([ 0.05647577, -0.31233884, -0.04303467,  0.06287278,  0.27366842,
         0.23542629]),
 array([ 0.52179489,  0.62166195, -0.23224796,  0.63010017,  0.57746874,
         0.00204579]),
 array([-0.04975812,  0.09690253, -0.23224796,  0.12385046,  0.00852415,
         0.19880463]),
 array([ 0.03419928,  0.1006484 ,  0.11762626,  0.06013815, -0.00106624,
        -0.02977174]),
 array([ 0.02874528, -0.0687122 , -0.01029924,  0.2557633 , -0.00106624,
        -0.1986

### Phase II

In [10]:
partition_percentage = 0.5
partition_size = int(n_layer_steps*n_layers_to_add*partition_percentage)
n_partition_weights = partition_size*n_qubits
n_sweeps = 2

In [11]:
print(layer_weights[:5])
print(n_partition_weights)
print(partition_size)

[array([-3.33066907e-17, -3.33066907e-17, -3.33066907e-17, -6.44598553e-01,
        7.11039243e-01,  5.38960658e-02]), array([ 5.93853627e-01, -1.11022302e-17, -1.11022302e-17, -4.05852921e-01,
        4.77207735e-01, -1.78902765e-01]), array([ 0.05616862, -0.86518922, -0.81036041, -0.4441426 ,  0.09794083,
        0.19445019]), array([-0.87340292, -0.30521581, -0.74609603, -0.4441426 ,  0.27872414,
        0.26348358]), array([ 0.24794572, -0.07122497,  1.08325849, -0.20645333, -0.0084622 ,
        1.25011822])]
30
5


In [12]:
#trainable_layers = layer_gates[:partition_size]
#trainable_weights = layer_weights[:partition_size]
#weights_flatten = np.concatenate(trainable_weights).ravel()

#is going to depend on the part of the circuit
@qml.qnode(dev)
def trainable_partition(params):
    
    if partition == 1:
        #apply trainable partition
        weights = []
        for i in range(partition_size):
            weights.append(params[int(i*n_qubits):int((i+1)*n_qubits)])
        
        for i in range(len(layer_gates[:partition_size])):
            apply_layer(layer_gates[:partition_size][i], weights[i])
            
        #apply non-trainable partition
        for i in range(len(layer_gates[partition_size:])):
            apply_layer(layer_gates[partition_size:][i], layer_weights[partition_size:][i])
        
    elif partition == 2:
        #apply non-trainable partition
        for i in range(len(layer_gates[:partition_size])):
            apply_layer(layer_gates[:partition_size][i], layer_weights[:partition_size][i])
    
        #apply trainable partition
        weights = []
        for i in range(partition_size):
            weights.append(params[int(i*n_qubits):int((i+1)*n_qubits)])
        
        for i in range(len(layer_gates[partition_size:])):
            apply_layer(layer_gates[partition_size:][i], weights[i])
            
    wirelist = [i for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix, wirelist))

In [13]:
def cost(x):
    
    return (1.0 - trainable_partition(x))

In [14]:
for sweep in range(n_sweeps):
    
    partition = 1
    trainable_weights = layer_weights[:partition_size]

    init_params = np.concatenate(trainable_weights).ravel()
    
    opt = qml.GradientDescentOptimizer(stepsize = 0.4)

    opt_steps = 100

    params = init_params
    
    for i in range(opt_steps):

        params = opt.step(cost, params)
        
    trained_weights = [params[int(i*n_qubits):int((i+1)*n_qubits)] for i in range(partition_size)]
    
    layer_weights[:partition_size] = trained_weights
    
    print(cost(params))

    partition = 2
    trainable_weights = layer_weights[partition_size:]

    init_params = np.concatenate(trainable_weights).ravel()
    
    opt = qml.GradientDescentOptimizer(stepsize = 0.4)

    opt_steps = 100

    params = init_params
    
    for i in range(opt_steps):

        params = opt.step(cost, params)
        
    trained_weights = [params[int(i*n_qubits):int((i+1)*n_qubits)] for i in range(partition_size)]
    
    layer_weights[partition_size:] = trained_weights
    
    print(cost(params))

0.26011872286748494
0.2213861559435124
0.21713070753458663
0.21245200699152922


### Complete-depth learning

In [15]:
@qml.qnode(dev)
def complete_depth_learning(params):
    
    weights = [params[int(i*n_qubits):int((i+1)*n_qubits)] for i in range(len(layer_gates))]
    
    for i in range(len(layer_gates)):
        apply_layer(layer_gates[i], weights[i])
        
    wirelist = [i for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix, wirelist))

In [16]:
def cost(x):
    
    return (1.0 - complete_depth_learning(x))

In [17]:
init_params = np.zeros(n_qubits*len(layer_gates))
    
opt = qml.GradientDescentOptimizer(stepsize = 0.4)

opt_steps = 200

params = init_params

for i in range(opt_steps):

    params = opt.step(cost, params)

print(cost(params))

0.21314824928299259
