In [1]:
import random

#Pennylane
import pennylane as qml
from pennylane import numpy as np

#PyTorch
import torch
import torchvision
from torchvision import datasets, transforms

In [2]:
dev = qml.device('default.qubit', wires = 6)
n_qubits = 6
n_layer_steps = 5
n_layers_to_add = 2
dim = 2**(n_qubits)

In [3]:
def set_random_gates(n_qubits: int):
    
    gate_set = [qml.RX, qml.RY, qml.RZ]
    chosen_gates = []
    for i in range(n_qubits):
        chosen_gate = random.choice(gate_set)
        chosen_gates.append(chosen_gate)
    return chosen_gates

def norm(complex_vector: np.array) -> float:
    """Returns the norm of a complex vector.
    
    Args:
       complex_vector (np.arrray of shape (dim,)):
           complex vector with an arbitrary dimension.
           
       
    Returns:
        norm (float): norm or magnitude of the complex vector.
            
    """
    
    #define the norm of a complex vector here
    norm = np.sqrt(sum([np.square(np.absolute(complex_vector[i])) for i in range(complex_vector.shape[0])]))
    
    return norm

def random_quantum_state(dim: int, amplitude_type: str = 'complex') -> np.array:
    """Creates a normalized random real or complex vector of a defined
    dimension.
    
    Args:
        dim (int): integer number specifying the dimension
            of the vector that we want to generate.
            
        amplitude_type (str): string indicating if you want to create a
            vector with 'complex' or 'real' number amplitudes.
            
    Returns:
        (np.array): normalized real or complex vector of the given
            dimension.
    """
    #generate an unnormalized complex vector of dimension = dim
    if amplitude_type == 'complex':
        Z = np.random.random(dim) + np.random.random(dim)*1j
    
    #generate an unnormalized real vector of dimension = dim
    elif amplitude_type == 'real':
        Z = np.random.random(dim)
    
    #normalize the complex vector Z
    Z /= norm(Z)
    
    return Z

def density_matrix(target_vector: np.array) -> np.array:
    """Return the density matrix of a pure state.
    
    Arguments:
        target_vector (np.array): Complex vector array.
        
    Returns:
        (np.array): Density matrix of shape (dim, dim),
            where dim is the dimension of the target_vector.
    """
    target_vector_reshape = target_vector.reshape((target_vector.shape[0],1))
    density_matrix = target_vector_reshape @ np.transpose(np.conjugate(target_vector_reshape))
    
    return density_matrix

In [4]:
target_vector = random_quantum_state(dim)
density_matrix = density_matrix(target_vector)

### Templates for Phase I

In [5]:
@qml.template
def apply_layer(gates, weights):
    
    for i in range(n_qubits):
        gates[i](weights[i], wires = i)
    
    tuples = [(i,i+1) for i in range(n_qubits-1)]

    for tup in tuples:
        qml.CZ(wires=[tup[0], tup[1]])
        
@qml.template #template for non-trainable part of the quantum circuit
def frozen_layers(frozen_layer_gates, frozen_layer_weights): 

    for i in range(len(frozen_layer_gates)):
        apply_layer(frozen_layer_gates[i], frozen_layer_weights[i])

@qml.qnode(dev)
def trainable_circuit(params):
    
    #apply frozen layers
    frozen_layers(layer_gates, layer_weights)
    
    #apply trainable layers
    new_weights = []
    for i in range(n_layers_to_add):
        new_weights.append(params[int(i*n_qubits):int((i+1)*n_qubits)])

    for i in range(n_layers_to_add):
        apply_layer(new_gates[i], new_weights[i])
        
    wirelist = [i for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix, wirelist))

In [6]:
def cost(x):
    
    return (1.0 - trainable_circuit(x))

In [7]:
layer_gates = []
layer_weights = []
n_layers = 2
for i in range(n_layers):
    layer_gates.append(set_random_gates(n_qubits))
    layer_weights.append(np.random.rand(n_qubits)*2*np.pi)
    
new_gates = [set_random_gates(n_qubits) for i in range(n_layers_to_add)]
params = np.random.rand(n_qubits*n_layers_to_add)*2*np.pi

trainable_circuit(params)

0.013567042037599394

In [8]:
layer_gates = []
layer_weights = []
cost_list = []
for step in range(n_layer_steps):
    
    new_gates = [set_random_gates(n_qubits) for i in range(n_layers_to_add)]
    init_params = np.zeros(n_qubits*n_layers_to_add)
    
    opt = qml.GradientDescentOptimizer(stepsize = 0.4)

    opt_steps = 100

    params = init_params
    
    for i in range(opt_steps):

        params = opt.step(cost, params)
    
    
    print(step)
    print(layer_weights)
    print(cost(params))
    cost_list.append(cost(params))
    
    trained_weights = [params[int(i*n_qubits):int((i+1)*n_qubits)] for i in range(n_layers_to_add)]
    
    layer_gates += new_gates
    layer_weights += trained_weights

0
[]
0.7436009708527992
1
[array([1.20530298e+00, 5.98970338e-01, 7.66347199e-01, 5.20417043e-18,
       1.43958492e+00, 1.53924839e+00]), array([ 0.2333933 ,  0.54202741,  0.45715828, -0.08118238,  0.28522425,
        0.09180399])]
0.7075565784016394
2
[array([1.20530298e+00, 5.98970338e-01, 7.66347199e-01, 5.20417043e-18,
       1.43958492e+00, 1.53924839e+00]), array([ 0.2333933 ,  0.54202741,  0.45715828, -0.08118238,  0.28522425,
        0.09180399]), array([-0.37943366,  0.29467347, -0.197845  , -0.09602041,  0.1117119 ,
        0.29619841]), array([ 0.11660583,  0.29467347, -0.21511868, -0.09602041,  0.09168672,
       -0.00256207])]
0.39229445367466587
3
[array([1.20530298e+00, 5.98970338e-01, 7.66347199e-01, 5.20417043e-18,
       1.43958492e+00, 1.53924839e+00]), array([ 0.2333933 ,  0.54202741,  0.45715828, -0.08118238,  0.28522425,
        0.09180399]), array([-0.37943366,  0.29467347, -0.197845  , -0.09602041,  0.1117119 ,
        0.29619841]), array([ 0.11660583,  0.29467

In [9]:
layer_weights

[array([1.20530298e+00, 5.98970338e-01, 7.66347199e-01, 5.20417043e-18,
        1.43958492e+00, 1.53924839e+00]),
 array([ 0.2333933 ,  0.54202741,  0.45715828, -0.08118238,  0.28522425,
         0.09180399]),
 array([-0.37943366,  0.29467347, -0.197845  , -0.09602041,  0.1117119 ,
         0.29619841]),
 array([ 0.11660583,  0.29467347, -0.21511868, -0.09602041,  0.09168672,
        -0.00256207]),
 array([-0.50110685,  0.06636442,  0.10156093,  1.59666545,  0.14523038,
        -0.11610741]),
 array([-0.01686726, -0.16010603,  0.07784774,  0.06174303, -0.00587617,
        -0.2425013 ]),
 array([-0.25486414,  0.26236452,  0.41614368, -0.12534002,  0.0391451 ,
         0.01870024]),
 array([-0.48621249,  0.26236452, -0.03580084, -0.13546174, -0.04371986,
        -0.00808908]),
 array([ 0.1725457 ,  0.03674968,  0.03178398, -0.01024755,  0.01251854,
        -0.01268638]),
 array([ 0.00068052,  0.18855207, -0.00999572, -0.24247306,  0.10701869,
        -0.01412737])]

### Phase II

In [10]:
partition_percentage = 0.5
partition_size = int(n_layer_steps*n_layers_to_add*partition_percentage)
n_partition_weights = partition_size*n_qubits
n_sweeps = 2

In [11]:
print(layer_weights[:5])
print(n_partition_weights)
print(partition_size)

[array([1.20530298e+00, 5.98970338e-01, 7.66347199e-01, 5.20417043e-18,
       1.43958492e+00, 1.53924839e+00]), array([ 0.2333933 ,  0.54202741,  0.45715828, -0.08118238,  0.28522425,
        0.09180399]), array([-0.37943366,  0.29467347, -0.197845  , -0.09602041,  0.1117119 ,
        0.29619841]), array([ 0.11660583,  0.29467347, -0.21511868, -0.09602041,  0.09168672,
       -0.00256207]), array([-0.50110685,  0.06636442,  0.10156093,  1.59666545,  0.14523038,
       -0.11610741])]
30
5


In [12]:
#trainable_layers = layer_gates[:partition_size]
#trainable_weights = layer_weights[:partition_size]
#weights_flatten = np.concatenate(trainable_weights).ravel()

#is going to depend on the part of the circuit
@qml.qnode(dev)
def trainable_partition(params):
    
    if partition == 1:
        #apply trainable partition
        weights = []
        for i in range(partition_size):
            weights.append(params[int(i*n_qubits):int((i+1)*n_qubits)])
        
        for i in range(len(layer_gates[:partition_size])):
            apply_layer(layer_gates[:partition_size][i], weights[i])
            
        #apply non-trainable partition
        for i in range(len(layer_gates[partition_size:])):
            apply_layer(layer_gates[partition_size:][i], layer_weights[partition_size:][i])
        
    elif partition == 2:
        #apply non-trainable partition
        for i in range(len(layer_gates[:partition_size])):
            apply_layer(layer_gates[:partition_size][i], layer_weights[:partition_size][i])
    
        #apply trainable partition
        weights = []
        for i in range(partition_size):
            weights.append(params[int(i*n_qubits):int((i+1)*n_qubits)])
        
        for i in range(len(layer_gates[partition_size:])):
            apply_layer(layer_gates[partition_size:][i], weights[i])
            
    wirelist = [i for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix, wirelist))

In [13]:
def cost(x):
    
    return (1.0 - trainable_partition(x))

In [14]:
for sweep in range(n_sweeps):
    
    partition = 1
    trainable_weights = layer_weights[:partition_size]

    init_params = np.concatenate(trainable_weights).ravel()
    
    opt = qml.GradientDescentOptimizer(stepsize = 0.4)

    opt_steps = 100

    params = init_params
    
    for i in range(opt_steps):

        params = opt.step(cost, params)
        
    trained_weights = [params[int(i*n_qubits):int((i+1)*n_qubits)] for i in range(partition_size)]
    
    layer_weights[:partition_size] = trained_weights
    
    print(cost(params))

    partition = 2
    trainable_weights = layer_weights[partition_size:]

    init_params = np.concatenate(trainable_weights).ravel()
    
    opt = qml.GradientDescentOptimizer(stepsize = 0.4)

    opt_steps = 100

    params = init_params
    
    for i in range(opt_steps):

        params = opt.step(cost, params)
        
    trained_weights = [params[int(i*n_qubits):int((i+1)*n_qubits)] for i in range(partition_size)]
    
    layer_weights[partition_size:] = trained_weights
    
    print(cost(params))

0.15779946577370296
0.15122895124610236
0.1503063459556906
0.14993383931630622
