In [5]:
!pip install --upgrade tensorflow==2.3.1

     |████████████████████████████████| 320.4 MB 84 kB/s  eta 0:00:01
     |████████████████████████████████| 20.1 MB 540 kB/s eta 0:00:01
     |████████████████████████████████| 459 kB 148 kB/s eta 0:00:01
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.4.0
    Uninstalling tensorflow-2.4.0:
      Successfully uninstalled tensorflow-2.4.0


In [6]:
!pip install tensorflow-quantum

     |████████████████████████████████| 5.9 MB 717 kB/s eta 0:00:01
     |████████████████████████████████| 1.6 MB 774 kB/s eta 0:00:01
     |████████████████████████████████| 5.6 MB 1.9 MB/s eta 0:00:01
     |████████████████████████████████| 92 kB 252 kB/s eta 0:00:01
     |████████████████████████████████| 100 kB 1.6 MB/s ta 0:00:01
     |████████████████████████████████| 512 kB 1.7 MB/s eta 0:00:01
     |████████████████████████████████| 1.3 MB 869 kB/s eta 0:00:01
     |████████████████████████████████| 9.9 MB 1.3 MB/s eta 0:00:01
     |████████████████████████████████| 510 kB 1.6 MB/s eta 0:00:01
  Created wheel for mpmath: filename=mpmath-1.1.0-py3-none-any.whl size=532239 sha256=a056f9bd60eca197ad514e0acf620365707ca425224bd7f321f687dcdd15bd82
  Stored in directory: /home/felipeoyarce/.cache/pip/wheels/e2/46/78/e78f76c356bca9277368f1f97a31b37a8cb937176d9511af31
Successfully built mpmath
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.14.0
    Uninsta

In [7]:
import collections
import itertools
import random
import copy

import cirq
import sympy
import numpy as np
import tensorflow_quantum as tfq
import tensorflow as tf
import matplotlib.pyplot as plt

NotFoundError: /home/felipeoyarce/Desktop/layerwise-learning/.venv/lib/python3.7/site-packages/tensorflow_quantum/core/ops/_tfq_simulate_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

In [4]:
for x, y in data_loader:
    print(model(x))
    print(y)

tensor([0.4741, 0.5358, 0.5833, 0.6760, 0.6889], grad_fn=<SigmoidBackward>)
tensor([1., 1., 1., 1., 1.])
tensor([0.5734, 0.3194, 0.7050, 0.4067, 0.4465], grad_fn=<SigmoidBackward>)
tensor([1., 0., 1., 1., 0.])
tensor([0.3077, 0.7050, 0.5538, 0.6657, 0.6425], grad_fn=<SigmoidBackward>)
tensor([0., 1., 0., 1., 1.])
tensor([0.3264, 0.6967, 0.6998, 0.3296, 0.5294], grad_fn=<SigmoidBackward>)
tensor([0., 1., 1., 0., 0.])
tensor([0.4895, 0.5816, 0.4269, 0.6941, 0.3047], grad_fn=<SigmoidBackward>)
tensor([1., 1., 0., 1., 0.])
tensor([0.3410, 0.4643, 0.3154, 0.6187, 0.4187], grad_fn=<SigmoidBackward>)
tensor([0., 0., 0., 1., 0.])
tensor([0.3055, 0.3995, 0.4168, 0.3602, 0.3668], grad_fn=<SigmoidBackward>)
tensor([0., 1., 1., 0., 0.])
tensor([0.6198, 0.4494, 0.5853, 0.5174, 0.6887], grad_fn=<SigmoidBackward>)
tensor([0., 0., 0., 1., 1.])
tensor([0.4046, 0.3468, 0.4163, 0.6851, 0.6310], grad_fn=<SigmoidBackward>)
tensor([0., 0., 0., 1., 1.])
tensor([0.7024, 0.4590, 0.6608, 0.5418, 0.6510], grad_f

tensor([0.6056, 0.7019, 0.6421, 0.4680, 0.6137], grad_fn=<SigmoidBackward>)
tensor([1., 1., 1., 1., 1.])
tensor([0.3786, 0.3059, 0.6627, 0.6996, 0.5984], grad_fn=<SigmoidBackward>)
tensor([0., 0., 1., 1., 0.])
tensor([0.7015, 0.3125, 0.3991, 0.5742, 0.4087], grad_fn=<SigmoidBackward>)
tensor([1., 0., 0., 0., 0.])
tensor([0.6734, 0.5536, 0.6447, 0.6020, 0.6780], grad_fn=<SigmoidBackward>)
tensor([1., 1., 1., 1., 1.])
tensor([0.5050, 0.3646, 0.6556, 0.4414, 0.6979], grad_fn=<SigmoidBackward>)
tensor([1., 0., 1., 1., 1.])
tensor([0.5880, 0.5906, 0.6644, 0.5685, 0.4248], grad_fn=<SigmoidBackward>)
tensor([0., 0., 1., 0., 1.])
tensor([0.4734, 0.5044, 0.4981, 0.5622, 0.3520], grad_fn=<SigmoidBackward>)
tensor([0., 0., 0., 1., 0.])
tensor([0.3624, 0.3152, 0.3383, 0.7036, 0.3810], grad_fn=<SigmoidBackward>)
tensor([0., 0., 0., 1., 0.])
tensor([0.7004, 0.3972, 0.6212, 0.5714, 0.3044], grad_fn=<SigmoidBackward>)
tensor([1., 1., 1., 0., 0.])
tensor([0.3897, 0.6044, 0.6286, 0.5263, 0.6878], grad_f